### ISSUE TITLE
Velikost slik pri nalaganju na stran

### ISSUE THREAD

**Issue by peterambrozic** [peterambrozic/testgit#2]
**predpogoji:**
Nameščen WordPress in dostop do backend-a.

**koraki za reproduciranje težave:**
1. Prijava na spletni strani,
2. izberemo meni media,
3. naložimo sliko.

**Pričakovani rezultat**
Možnost nalaganja slik večje od 1 MB.

**Dejanski rezultat**
![slika](https://user-images.githubusercontent.com/35289735/35184419-b9f3728a-fdf5-11e7-9540-fdf40860618b.png)

**Comment by botNet1994** [comment]
Velikosti slike lahko spremenimo direktno v nastavitvah CMS-a, lahko pa tudi v datoteki "wp-config.cfg". spremenimo max upload size na želeno vrednost
